
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/docker/go-connections"

[[constraint]]
  name = "github.com/gorilla/websocket"

[[constraint]]
  name = "github.com/jhoonb/archivex"

[[constraint]]
  name = "github.com/metrue/fx"

[[constraint]]
  name = "github.com/phayes/freeport"

[[constraint]]
  name = "github.com/rs/xid"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  version = "3.0.7"

[[constraint]]
  name = "github.com/golang/protobuf/proto"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
