[package]
name = "rust"
version = "0.1.0"
authors = ["FrontMage <xbgxwh@outlook.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.7"
rocket_contrib = "0.4.0-rc.2"
serde_json = "1.0"
serde_derive = "1.0.70"
serde = "1.0.70"

